# Generated by Django 4.1.2 on 2022-10-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='Nombre')),
                ('edad', models.IntegerField()),
                ('universo', models.CharField(choices=[('1', 'Marvel'), ('2', 'DC')], max_length=1, verbose_name='Universo')),
            ],
        ),
    ]
