# Generated by Django 4.0.6 on 2022-10-31 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('amount', models.PositiveIntegerField(verbose_name='Monto')),
                ('operation_type', models.CharField(choices=[('1', 'Deposit'), ('2', 'Extraction'), ('3', 'Transfer')], max_length=1)),
                ('credit_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Acreditaciones', to='account.account', verbose_name='Destino')),
                ('debit_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Extracciones', to='account.account', verbose_name='Partida')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Tracciones',
            },
        ),
    ]
