# Generated by Django 4.1.4 on 2022-12-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('token', models.IntegerField(unique=True)),
            ],
        ),
    ]
