# Generated by Django 4.1.4 on 2022-12-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_alter_usuario_email_alter_usuario_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idUser',
            new_name='idUsuario',
        ),
    ]
