# Generated by Django 4.1.4 on 2022-12-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0003_rename_iduser_usuario_idusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('idNotas', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Titulo', models.CharField(max_length=45)),
                ('descrip', models.CharField(max_length=45)),
                ('estado', models.CharField(choices=[('1', 'Aprobado'), ('2', 'Desaprobado'), ('3', 'Verificando')], max_length=1, verbose_name='Estado')),
                ('fechCreacion', models.DateField()),
                ('fechCierre', models.DateField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
    ]
